/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Client {
  'id' : ClientId,
  'contact' : string,
  'name' : string,
  'rate' : number,
  'address' : string,
}
export type ClientId = number;
export interface DashboardData {
  'clientId' : ClientId,
  'openAmount' : number,
  'openHours' : number,
}
export interface Expense {
  'id' : ExpenseId,
  'clientId' : ClientId,
  'date' : bigint,
  'description' : string,
  'amount' : number,
}
export type ExpenseId = number;
export interface Invoice {
  'id' : InvoiceId,
  'status' : InvoiceStatus,
  'month' : number,
  'clientId' : ClientId,
  'netAmount' : number,
  'smallExpenseFlatRate' : number,
  'year' : number,
  'createdDate' : bigint,
  'grossAmount' : number,
  'timeEntryIds' : Uint32Array,
  'expenseIds' : Uint32Array,
  'vatAmount' : number,
  'vatRate' : number,
}
export type InvoiceId = number;
export type InvoiceStatus = { 'sent' : null } |
  { 'draft' : null };
export interface Settings {
  'smallExpenseFlatRate' : number,
  'address' : string,
  'companyName' : string,
  'standardRate' : number,
  'vatRate' : number,
}
export interface TimeEntry {
  'id' : TimeEntryId,
  'startTime' : bigint,
  'duration' : number,
  'clientId' : ClientId,
  'endTime' : bigint,
  'date' : bigint,
  'description' : string,
  'amount' : number,
}
export type TimeEntryId = number;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClient' : ActorMethod<[string, string, number, string], ClientId>,
  'createExpense' : ActorMethod<[ClientId, bigint, number, string], ExpenseId>,
  'createTimeEntry' : ActorMethod<
    [ClientId, bigint, bigint, bigint, string],
    TimeEntryId
  >,
  'deleteClient' : ActorMethod<[ClientId], undefined>,
  'deleteExpense' : ActorMethod<[ExpenseId], undefined>,
  'deleteTimeEntry' : ActorMethod<[TimeEntryId], undefined>,
  'generateInvoice' : ActorMethod<[ClientId, number, number], InvoiceId>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllExpenses' : ActorMethod<[], Array<Expense>>,
  'getAllInvoices' : ActorMethod<[], Array<Invoice>>,
  'getAllTimeEntries' : ActorMethod<[], Array<TimeEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[ClientId], [] | [Client]>,
  'getDashboardData' : ActorMethod<[], Array<DashboardData>>,
  'getExpense' : ActorMethod<[ExpenseId], [] | [Expense]>,
  'getInvoice' : ActorMethod<[InvoiceId], [] | [Invoice]>,
  'getSettings' : ActorMethod<[], Settings>,
  'getTimeEntry' : ActorMethod<[TimeEntryId], [] | [TimeEntry]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendInvoice' : ActorMethod<[InvoiceId], undefined>,
  'updateClient' : ActorMethod<[Client], undefined>,
  'updateExpense' : ActorMethod<[Expense], undefined>,
  'updateSettings' : ActorMethod<[Settings], undefined>,
  'updateTimeEntry' : ActorMethod<[TimeEntry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];