/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ClientId = IDL.Nat32;
export const ExpenseId = IDL.Nat32;
export const TimeEntryId = IDL.Nat32;
export const InvoiceId = IDL.Nat32;
export const Client = IDL.Record({
  'id' : ClientId,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'rate' : IDL.Float64,
  'address' : IDL.Text,
});
export const Expense = IDL.Record({
  'id' : ExpenseId,
  'clientId' : ClientId,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const InvoiceStatus = IDL.Variant({
  'sent' : IDL.Null,
  'draft' : IDL.Null,
});
export const Invoice = IDL.Record({
  'id' : InvoiceId,
  'status' : InvoiceStatus,
  'month' : IDL.Nat8,
  'clientId' : ClientId,
  'netAmount' : IDL.Float64,
  'smallExpenseFlatRate' : IDL.Float64,
  'year' : IDL.Nat16,
  'createdDate' : IDL.Int,
  'grossAmount' : IDL.Float64,
  'timeEntryIds' : IDL.Vec(TimeEntryId),
  'expenseIds' : IDL.Vec(ExpenseId),
  'vatAmount' : IDL.Float64,
  'vatRate' : IDL.Float64,
});
export const TimeEntry = IDL.Record({
  'id' : TimeEntryId,
  'startTime' : IDL.Int,
  'duration' : IDL.Float64,
  'clientId' : ClientId,
  'endTime' : IDL.Int,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const DashboardData = IDL.Record({
  'clientId' : ClientId,
  'openAmount' : IDL.Float64,
  'openHours' : IDL.Float64,
});
export const Settings = IDL.Record({
  'smallExpenseFlatRate' : IDL.Float64,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'standardRate' : IDL.Float64,
  'vatRate' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
      [ClientId],
      [],
    ),
  'createExpense' : IDL.Func(
      [ClientId, IDL.Int, IDL.Float64, IDL.Text],
      [ExpenseId],
      [],
    ),
  'createTimeEntry' : IDL.Func(
      [ClientId, IDL.Int, IDL.Int, IDL.Int, IDL.Text],
      [TimeEntryId],
      [],
    ),
  'deleteClient' : IDL.Func([ClientId], [], []),
  'deleteExpense' : IDL.Func([ExpenseId], [], []),
  'deleteTimeEntry' : IDL.Func([TimeEntryId], [], []),
  'generateInvoice' : IDL.Func(
      [ClientId, IDL.Nat8, IDL.Nat16],
      [InvoiceId],
      [],
    ),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
  'getAllTimeEntries' : IDL.Func([], [IDL.Vec(TimeEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
  'getDashboardData' : IDL.Func([], [IDL.Vec(DashboardData)], ['query']),
  'getExpense' : IDL.Func([ExpenseId], [IDL.Opt(Expense)], ['query']),
  'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getTimeEntry' : IDL.Func([TimeEntryId], [IDL.Opt(TimeEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendInvoice' : IDL.Func([InvoiceId], [], []),
  'updateClient' : IDL.Func([Client], [], []),
  'updateExpense' : IDL.Func([Expense], [], []),
  'updateSettings' : IDL.Func([Settings], [], []),
  'updateTimeEntry' : IDL.Func([TimeEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ClientId = IDL.Nat32;
  const ExpenseId = IDL.Nat32;
  const TimeEntryId = IDL.Nat32;
  const InvoiceId = IDL.Nat32;
  const Client = IDL.Record({
    'id' : ClientId,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'rate' : IDL.Float64,
    'address' : IDL.Text,
  });
  const Expense = IDL.Record({
    'id' : ExpenseId,
    'clientId' : ClientId,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const InvoiceStatus = IDL.Variant({ 'sent' : IDL.Null, 'draft' : IDL.Null });
  const Invoice = IDL.Record({
    'id' : InvoiceId,
    'status' : InvoiceStatus,
    'month' : IDL.Nat8,
    'clientId' : ClientId,
    'netAmount' : IDL.Float64,
    'smallExpenseFlatRate' : IDL.Float64,
    'year' : IDL.Nat16,
    'createdDate' : IDL.Int,
    'grossAmount' : IDL.Float64,
    'timeEntryIds' : IDL.Vec(TimeEntryId),
    'expenseIds' : IDL.Vec(ExpenseId),
    'vatAmount' : IDL.Float64,
    'vatRate' : IDL.Float64,
  });
  const TimeEntry = IDL.Record({
    'id' : TimeEntryId,
    'startTime' : IDL.Int,
    'duration' : IDL.Float64,
    'clientId' : ClientId,
    'endTime' : IDL.Int,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const DashboardData = IDL.Record({
    'clientId' : ClientId,
    'openAmount' : IDL.Float64,
    'openHours' : IDL.Float64,
  });
  const Settings = IDL.Record({
    'smallExpenseFlatRate' : IDL.Float64,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'standardRate' : IDL.Float64,
    'vatRate' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Text],
        [ClientId],
        [],
      ),
    'createExpense' : IDL.Func(
        [ClientId, IDL.Int, IDL.Float64, IDL.Text],
        [ExpenseId],
        [],
      ),
    'createTimeEntry' : IDL.Func(
        [ClientId, IDL.Int, IDL.Int, IDL.Int, IDL.Text],
        [TimeEntryId],
        [],
      ),
    'deleteClient' : IDL.Func([ClientId], [], []),
    'deleteExpense' : IDL.Func([ExpenseId], [], []),
    'deleteTimeEntry' : IDL.Func([TimeEntryId], [], []),
    'generateInvoice' : IDL.Func(
        [ClientId, IDL.Nat8, IDL.Nat16],
        [InvoiceId],
        [],
      ),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getAllInvoices' : IDL.Func([], [IDL.Vec(Invoice)], ['query']),
    'getAllTimeEntries' : IDL.Func([], [IDL.Vec(TimeEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
    'getDashboardData' : IDL.Func([], [IDL.Vec(DashboardData)], ['query']),
    'getExpense' : IDL.Func([ExpenseId], [IDL.Opt(Expense)], ['query']),
    'getInvoice' : IDL.Func([InvoiceId], [IDL.Opt(Invoice)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getTimeEntry' : IDL.Func([TimeEntryId], [IDL.Opt(TimeEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendInvoice' : IDL.Func([InvoiceId], [], []),
    'updateClient' : IDL.Func([Client], [], []),
    'updateExpense' : IDL.Func([Expense], [], []),
    'updateSettings' : IDL.Func([Settings], [], []),
    'updateTimeEntry' : IDL.Func([TimeEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };